services:
    wakbook-api:
        image: ghcr.io/theovauvilliers/wakbook-api:${IMAGE_TAG:-latest}
        container_name: wakbook-api
        restart: unless-stopped
        env_file:
            - .env
        depends_on: [ wakbook-db ]
        volumes:
            - ./.env:/var/www/html/.env:ro
        ports: [ ]
        networks:
            - wakbook
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.wakbook-api.rule=Host(`wakbook-api.theovauvilliers.dev`)
            - traefik.http.routers.wakbook-api.entrypoints=websecure
            - traefik.http.routers.wakbook-api.tls.certresolver=cloudflare
            - traefik.http.routers.wakbook-api.middlewares=secure-headers@file
            - traefik.http.services.wakbook-api.loadbalancer.server.port=80

    wakbook-db:
        image: postgres:16-alpine
        restart: unless-stopped
        container_name: wakbook-db
        env_file:
            -   .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - wakbook_db_data:/var/lib/postgresql/data:rw
        networks:
            - wakbook

volumes:
    wakbook_db_data:

networks:
    wakbook:
        name: wakbook
    proxy:
        external: true
        name: proxy
